### ISSUE TITLE
Slack RTM errors

### ISSUE THREAD

**Issue by chrissexton** [velour/chat#38]
Errors from the Slack RTM API appear to be broken.

From the Slack docs:

> Errors
>
> If there is an error processing an event the message server will reply with an error. For example:
> 
> {
>     "ok": false,
>     "reply_to": 1,
>     "error": {
>         "code": 2,
>         "msg": "message text is missing"
>     }
> }

The panic that we see:

```
Message{
        ID: "293"
        From: User{
                ID: "216626902"
                Nick: "jelca"
                Name: "eaburns"
                PhotoURL: "https://bridge.chrissexton.org/telegram/media/AgADAQADuKcxG9Z26QwoVjB7QEOC2uwD6C8ABL74M-oiQSr90SoAAgI"
        }
        Text: "maybe tomorrow"
}
panic: json: cannot unmarshal string into Go value of type struct { Code uint64 "json:\"code\""; Msg string "json:\"msg\"" }

goroutine 1 [running]:
panic(0x66d1c0, 0xc4202d05a0)
        /home/cws/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /home/cws/src/github.com/velour/chat/bridge/main.go:120 +0xa47
exit status 2
```

And the file/line where it is relevant: [slack/message.go#L29](https://github.com/velour/chat/blob/master/slack/message.go#L29)

**Comment by eaburns** [comment]
I'm curious how adding ResponseError fixed trying to deserialize a string into `struct {int64;string;}`. Whas this stuff just all out of whack?

**Comment by chrissexton** [comment]
I think I was just tired when I added ResponseError to Update. It was just out of whack with the wrong struct being populated when Slack sends messages. Update is reserved for the RTM things.

**Comment by eaburns** [comment]
Oh. So Update isn't even the response from that method?

**Comment by chrissexton** [comment]
@eaburns noooope 😃
