### ISSUE TITLE
Corrupted links with '_'

### ISSUE THREAD

**Issue by chrissexton** [velour/chat#68]
A link coming from slack:

http://68.media.tumblr.com/616e3b0fbddb3c22c459b857f8661000/tumblr_ojfpm4Yu231rpf0t3o1_500.jpg

had its underscores stripped out when it got to Telegram (but not IRC):

http://68.media.tumblr.com/616e3b0fbddb3c22c459b857f8661000/tumblrojfpm4Yu231rpf0t3o1500.jpg

Probably due to markdown stuff.

**Comment by eaburns** [comment]
I think we should turn off markdown for Telegram for now. It's buggy.
